site_name: PACI 2022 Dados Abertos

# Repository
repo_name: transparencia-mg/PACI-2022
repo_url: http://github.com/transparencia-mg/PACI-2022
edit_uri: edit/main/docs/

nav:
  - PÁGINA INICIAL: 'index.md'
  - 1 BASES APRESENTADAS E CRITÉRIOS PARA ABERTURA: 'criterios-abertura.md'
  - 2 PANORAMA: 'previa-avaliacao.md'
  - 3 AVALIAÇÃO:
    - 3.1. PLENO: 'pleno.md'
    - 3.2. SUFICIENTE: 'suficiente.md'
    - 3.3. INCIPIENTE: 'incipiente.md'
  - 4 REUNIÕES: '2022-12-28.md'  

# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

