site_name: PACI 2022 Dados Abertos - Panorama e Avaliação

# Repository
repo_name: Andrelamor/PACI-2022
repo_url: http://github.com/Andrelamor/PACI-2022
edit_uri: edit/main/docs/

nav:
  - 1 PANORAMA: 'previa-avaliacao.md'
  - 2 AVALIAÇÃO: 'criterios-avaliacao.md'
    - 2.1. CRITÉRIOS: ''
  - 3 BASES PARA ABERTURA
    - 3.1. CRITÉRIOS: ''


# Configuration
theme:
  name: material
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

